# Generated by Django 4.0.3 on 2022-03-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_member_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
